import express from "express";
import mongoose from "mongoose";

//  A schema defines the structure of documents in a MongoDB collection.


const userSchema = new mongoose.Schema(
    // Define Structure of user Database
    {
        _id : {type : String , required : true},
        name:{type : String , required : true},
        email:{type : String , required : true},
        imageUrl:{type : String , required : true}, // URL to user Profile image
        enrolledCourses: [
            {
                type:mongoose.Schema.Types.ObjectId,
                ref: 'Course'
            } /*
                This field stores MongoDB ObjectIds, which are special unique identifiers.
                Each ObjectId here represents a reference to a course the user has enrolled in.
                MongoDB automatically generates a unique _id (which is an ObjectId) for each course document in the Course collection — unless you manually specify one.
                In the userSchema, the enrolledCourses array stores those ObjectIds (auto-generated by MongoDB for each course) as references to know which courses the user is enrolled in.
             */
        ]
    } , {timestamps:true}); /* This enables automatic creation of two fields in the document:
                                createdAt: When the document was first created.
                                updatedAt: When the document was last updated.*/

// user model

const User = mongoose.model('User' , userSchema) 

export default User
